# Generated by Django 4.2.7 on 2023-11-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estampagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estampagens',
            name='ae',
            field=models.IntegerField(),
        ),
    ]
